# -*- coding: utf-8 -*-
"""Charan_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LymyZn-84U-Ew8J24kERbNhyatHxHC7F
"""

from google.colab import drive
drive.mount('/content/drive')

#Importing Lirbraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Loading the dataset
nba_df=pd.read_csv('/content/drive/MyDrive/NBA_data')

#printing first five rows
nba_df.head()

#checking the null values in the dataset
nba_df.isnull().sum()

#Total columns present in it
nba_df.columns

#Replace the values with mean values
print(nba_df.fillna(nba_df.mean()).isnull().sum())

#Replace tha 'NaN' values with '0'
nba_df['Threepoint Attempt rate']=nba_df['Threepoint Attempt rate'].fillna(0)
nba_df.head()

#Displaying the statistical Measures
nba_df.describe()

#Dimensions of Dataset and info of dataset
print(nba_df.info())
nba_df.shape

#No of players of Each Position
nba_df['Position'].value_counts()

#Data Visualization

plt.figure(figsize=(10,5))
plt.title('Scatter Plot')
for i in nba_df.columns:
  plt.scatter(x=nba_df[i],y=nba_df['Player Efficiency Rating'])
  plt.xlabel(i)
  plt.ylabel('Player Efficiency Rating')
  plt.show()

#Find the correlation among the columns to find the dependent and independent columns
plt.figure(figsize=(15,8))
plt.title('To Find Dependent And Independent Variables')
sns.heatmap(nba_df.corr(),annot=True)
plt.show()

# From the heatmap we identify the independent terms are Age, Free Throw Attempt
#Player Efficiency and True Shooting are strongly Correlated

#BarPlot
plt.figure(figsize=(18,5))
plt.title('BarPlot')
sns.barplot(nba_df['Free throw attempt rate'],nba_df['Player Efficiency Rating'])
plt.show()

#PairPlot
sns.pairplot(nba_df[['Threepoint Attempt rate','Free throw attempt rate','Player Efficiency Rating']])

y=nba_df.iloc[:,4]
y

type(y)